### ISSUE TITLE
rest of the code

### ISSUE THREAD

**Issue by sophia-wright-blue** [karolmajek/YoloV3-Open-Images-v4#1]
Hello,

this repo is exactly what I was looking for! do you plan to upload the rest of the code in the near future?

Thanks,

**Comment by karolmajek** [comment]
Hello,
I was looking for something similar, but I haven't found any, so I created this repo.
There are many problems:

1. download Open Images V4 (it's not so easy)
2. convert to YoloV3
3. prepare darknet yolov3 params
4. debug training
5. get good results

I have few other things to do now, so can't guarantee I will finish this soon
I'm now between 1 and 4, not sure if I downloaded OID4 correctly, have some conversion, but training gives no results as I remember.

Thanks for writing to me, this adds some extra motivation to finish this :-)
Karol

**Comment by sophia-wright-blue** [comment]
thanks for the detailed reply, have you come across this repo: https://github.com/radekosmulski/yolo_open_images

the description and links there might be helpful.

i'll follow the steps you mentioned and try to train yolo-v3 on open images. i plan on using a pytorch yolo-v3 implementation. will send you an update if I make any progress.

looking forward to updates from you!

**Comment by TengFei75882341** [comment]
looking forward to updates from you too !!! @karolmajek

**Comment by karolmajek** [comment]
Video of YOLOv3 OIDv4: https://youtu.be/v_E5tO6yReU

@sophia-wright-blue
I was able to run YOLOv3 trained by @radekosmulski

I will delete this repo and create new one this year (I hope so) with full instructions how to train

**Comment by sophia-wright-blue** [comment]
thanks so much for letting me know @karolmajek ! i've been busy with another project, but want to get back to this one, looking forward to the new repo - please let me know when it's ready, good luck and thanks again!

**Comment by karolmajek** [comment]
No problem. It will be hard for me to remember to let you know.
I don't have any solution for this.

**Comment by sophia-wright-blue** [comment]
no worries @karolmajek , i'll follow you on github, look forward to see more updates from you! good luck!
